name: Publish NuGet packages

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      tag-name:
        description: The name of the tag for the Github release to upload the packages to.
        type: string
        required: true

      cache-nuget:
        description: Whether .NET packages should be locked and cached.
        type: boolean
        default: false

      nuget-lock-path:
        description: The path to the packages.lock.json file to use.
        type: string
        default: src/packages.lock.json

    secrets:
        NUGET_TOKEN:
          description: The API token required for uploading packages to NuGet.
          required: true

jobs:
  dotnet_pack:
    uses: ./.github/workflows/dotnet_pack.yml
    with:
      cache-nuget: ${{ inputs.cache-nuget }}
      nuget-lock-path: ${{ inputs.nuget-lock-path }}

  nuget_upload:
    needs: dotnet_pack
    uses: ./.github/workflows/upload_nuget.yml
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    with:
      artifact-id: ${{ needs.dotnet_pack.outputs.artifact-id }}

  release_upload:
    needs: dotnet_pack
    uses: ./.github/workflows/upload_nuget_release.yml
    with:
      artifact-id: ${{ needs.dotnet_pack.outputs.artifact-id }}
      tag-name: ${{ inputs.tag-name }}