permissions:
  contents: read

on:
  workflow_call: # Required for reusable workflows.
    inputs:
      dotnet-version:
        description: The .NET version to install.
        type: string
        default: '9'

      artifact-id:
        description: The id of the artifact to download from the workflow and then upload to NuGet.
        type: string
        required: true

      endpoint:
        description: The NuGet endpoint to upload the packages to.
        type: string
        default: https://api.nuget.org/v3/index.json

      skip-duplicates:
        description: Whether duplicate packages should be skipped.
        type: boolean
        default: true

    secrets:
        NUGET_TOKEN:
          description: The API token required for uploading packages to NuGet.
          required: true

jobs:
  upload_nuget:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Install the .NET workflow.
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Download artifact packages.
        uses: actions/download-artifact@v5
        with:
          artifact-ids: ${{ inputs.artifact-id }}
          path: "${{ runner.temp }}/nuget_packages"
          merge-multiple: true

      - name: Upload packages to NuGet.
        run: |
            if [ "${{ inputs.skip-duplicates }}" == "true" ]; then
              dotnet nuget push "${{ runner.temp }}/nuget_packages/*" --api-key $NUGET_TOKEN --source ${{ inputs.endpoint }} --skip-duplicate
            else
              dotnet nuget push "${{ runner.temp }}/nuget_packages/*" --api-key $NUGET_TOKEN --source ${{ inputs.endpoint }}
            fi
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
